/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HelpRouteImport } from './routes/help'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerSettingsRouteImport } from './routes/seller.settings'
import { Route as SellerReviewsRouteImport } from './routes/seller.reviews'
import { Route as SellerReturnsRouteImport } from './routes/seller.returns'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerPayoutsRouteImport } from './routes/seller.payouts'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerMessagesRouteImport } from './routes/seller.messages'
import { Route as SellerInventoryRouteImport } from './routes/seller.inventory'
import { Route as SellerDashboardRouteImport } from './routes/seller.dashboard'
import { Route as SellerCustomersRouteImport } from './routes/seller.customers'
import { Route as SellerCouponsRouteImport } from './routes/seller.coupons'
import { Route as SellerAnalyticsRouteImport } from './routes/seller.analytics'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminReturnsRouteImport } from './routes/admin.returns'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSettingsRoute = SellerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SellerRoute,
} as any)
const SellerReviewsRoute = SellerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SellerRoute,
} as any)
const SellerReturnsRoute = SellerReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerPayoutsRoute = SellerPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerMessagesRoute = SellerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => SellerRoute,
} as any)
const SellerInventoryRoute = SellerInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => SellerRoute,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SellerRoute,
} as any)
const SellerCustomersRoute = SellerCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => SellerRoute,
} as any)
const SellerCouponsRoute = SellerCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAnalyticsRoute = SellerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SellerRoute,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/coupons': typeof CouponsRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/refer': typeof ReferRoute
  '/seller': typeof SellerRouteWithChildren
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/wishlist': typeof WishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/coupons': typeof SellerCouponsRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/inventory': typeof SellerInventoryRoute
  '/seller/messages': typeof SellerMessagesRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payouts': typeof SellerPayoutsRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/returns': typeof SellerReturnsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/coupons': typeof CouponsRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/refer': typeof ReferRoute
  '/seller': typeof SellerRouteWithChildren
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/wishlist': typeof WishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/coupons': typeof SellerCouponsRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/inventory': typeof SellerInventoryRoute
  '/seller/messages': typeof SellerMessagesRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payouts': typeof SellerPayoutsRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/returns': typeof SellerReturnsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/coupons': typeof CouponsRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/refer': typeof ReferRoute
  '/seller': typeof SellerRouteWithChildren
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/wishlist': typeof WishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/coupons': typeof SellerCouponsRoute
  '/seller/customers': typeof SellerCustomersRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/inventory': typeof SellerInventoryRoute
  '/seller/messages': typeof SellerMessagesRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payouts': typeof SellerPayoutsRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/returns': typeof SellerReturnsRoute
  '/seller/reviews': typeof SellerReviewsRoute
  '/seller/settings': typeof SellerSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/coupons'
    | '/help'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/refer'
    | '/seller'
    | '/settings'
    | '/wallet'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/commissions'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/transactions'
    | '/admin/users'
    | '/product/$productId'
    | '/seller/analytics'
    | '/seller/coupons'
    | '/seller/customers'
    | '/seller/dashboard'
    | '/seller/inventory'
    | '/seller/messages'
    | '/seller/orders'
    | '/seller/payouts'
    | '/seller/products'
    | '/seller/returns'
    | '/seller/reviews'
    | '/seller/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/coupons'
    | '/help'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/refer'
    | '/seller'
    | '/settings'
    | '/wallet'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/commissions'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/transactions'
    | '/admin/users'
    | '/product/$productId'
    | '/seller/analytics'
    | '/seller/coupons'
    | '/seller/customers'
    | '/seller/dashboard'
    | '/seller/inventory'
    | '/seller/messages'
    | '/seller/orders'
    | '/seller/payouts'
    | '/seller/products'
    | '/seller/returns'
    | '/seller/reviews'
    | '/seller/settings'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/coupons'
    | '/help'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/refer'
    | '/seller'
    | '/settings'
    | '/wallet'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/commissions'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/returns'
    | '/admin/sellers'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/transactions'
    | '/admin/users'
    | '/product/$productId'
    | '/seller/analytics'
    | '/seller/coupons'
    | '/seller/customers'
    | '/seller/dashboard'
    | '/seller/inventory'
    | '/seller/messages'
    | '/seller/orders'
    | '/seller/payouts'
    | '/seller/products'
    | '/seller/returns'
    | '/seller/reviews'
    | '/seller/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  CouponsRoute: typeof CouponsRoute
  HelpRoute: typeof HelpRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  ReferRoute: typeof ReferRoute
  SellerRoute: typeof SellerRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  WalletRoute: typeof WalletRoute
  WishlistRoute: typeof WishlistRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/settings': {
      id: '/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof SellerSettingsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/reviews': {
      id: '/seller/reviews'
      path: '/reviews'
      fullPath: '/seller/reviews'
      preLoaderRoute: typeof SellerReviewsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/returns': {
      id: '/seller/returns'
      path: '/returns'
      fullPath: '/seller/returns'
      preLoaderRoute: typeof SellerReturnsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/payouts': {
      id: '/seller/payouts'
      path: '/payouts'
      fullPath: '/seller/payouts'
      preLoaderRoute: typeof SellerPayoutsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/messages': {
      id: '/seller/messages'
      path: '/messages'
      fullPath: '/seller/messages'
      preLoaderRoute: typeof SellerMessagesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/inventory': {
      id: '/seller/inventory'
      path: '/inventory'
      fullPath: '/seller/inventory'
      preLoaderRoute: typeof SellerInventoryRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/customers': {
      id: '/seller/customers'
      path: '/customers'
      fullPath: '/seller/customers'
      preLoaderRoute: typeof SellerCustomersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/coupons': {
      id: '/seller/coupons'
      path: '/coupons'
      fullPath: '/seller/coupons'
      preLoaderRoute: typeof SellerCouponsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/analytics': {
      id: '/seller/analytics'
      path: '/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof SellerAnalyticsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SellerRouteChildren {
  SellerAnalyticsRoute: typeof SellerAnalyticsRoute
  SellerCouponsRoute: typeof SellerCouponsRoute
  SellerCustomersRoute: typeof SellerCustomersRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerInventoryRoute: typeof SellerInventoryRoute
  SellerMessagesRoute: typeof SellerMessagesRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerPayoutsRoute: typeof SellerPayoutsRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerReturnsRoute: typeof SellerReturnsRoute
  SellerReviewsRoute: typeof SellerReviewsRoute
  SellerSettingsRoute: typeof SellerSettingsRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerAnalyticsRoute: SellerAnalyticsRoute,
  SellerCouponsRoute: SellerCouponsRoute,
  SellerCustomersRoute: SellerCustomersRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  SellerInventoryRoute: SellerInventoryRoute,
  SellerMessagesRoute: SellerMessagesRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerPayoutsRoute: SellerPayoutsRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerReturnsRoute: SellerReturnsRoute,
  SellerReviewsRoute: SellerReviewsRoute,
  SellerSettingsRoute: SellerSettingsRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  CouponsRoute: CouponsRoute,
  HelpRoute: HelpRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  ReferRoute: ReferRoute,
  SellerRoute: SellerRouteWithChildren,
  SettingsRoute: SettingsRoute,
  WalletRoute: WalletRoute,
  WishlistRoute: WishlistRoute,
  ProductProductIdRoute: ProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
